main: me.ChestOrganizer.main.ChestOrganizer
name: ChestOrganizer
author: CJM
version: 1.1
api-version: 1.14
description: Players can auto organize chests

commands:
   ChestOrganizer:
      usage: /ChestOrganizer
      aliases: [co]
      
permissions:
   ChestOrganizer.SortContainer:
      description: Allowed to sort contatiners
      default: true
   ChestOrganizer.SortPlayerInventory:
      description: Allowed to sort own player inventory
      default: true
   ChestOrganizer.SortPlayerInventory.Other:
      description: Allowed to sort other players inventory
      default: false